"""Validate serialized author cases against public CompanyResearchRun models only."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from company_bi.models import CompanyResearchRun

BOUNDARY = {"IDENTITY_INVALID", "PROVENANCE_INVALID"}
CLASSIFICATIONS = {
    "SUPPORTED_CONTRACT_POSITIVE",
    "OUT_OF_CONTRACT_TRUE",
    "UNSAFE_NEGATIVE",
    "IDENTITY_INVALID",
    "PROVENANCE_INVALID",
}


def preflight(path: Path) -> tuple[list[dict[str, Any]], bool]:
    try:
        cases = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return [
            {"case_id": None, "status": "INVALID", "detail": f"cannot read JSON: {error}"}
        ], False
    if not isinstance(cases, list):
        cases = [cases]
    if not cases:
        return [
            {
                "case_id": None,
                "status": "INVALID",
                "detail": "corpus must contain at least one case",
            }
        ], False
    results: list[dict[str, Any]] = []
    seen: set[str] = set()
    failed = False
    for index, case in enumerate(cases):
        case_id = case.get("case_id") if isinstance(case, dict) else None
        classification = case.get("classification") if isinstance(case, dict) else None
        if (
            not isinstance(case, dict)
            or not isinstance(case_id, str)
            or not case_id.strip()
            or not isinstance(case.get("run"), dict)
            or not isinstance(classification, str)
            or classification not in CLASSIFICATIONS
            or not isinstance(case.get("expected_action"), str)
            or case.get("expected_action") not in {"publish", "abstain", "reject"}
            or not isinstance(case.get("path"), str)
            or not case["path"]
        ):
            results.append(
                {
                    "case_id": case_id,
                    "status": "INVALID",
                    "detail": f"case {index}: missing required case shape",
                }
            )
            failed = True
            continue
        if case_id in seen:
            results.append({"case_id": case_id, "status": "INVALID", "detail": "duplicate case_id"})
            failed = True
            continue
        seen.add(case_id)
        try:
            CompanyResearchRun.model_validate_json(json.dumps(case["run"], ensure_ascii=False))
        except ValidationError as error:
            if classification in BOUNDARY:
                intentional_invalid = case["expected_action"] == "reject"
                annotation = (
                    "expected-invalid boundary control; manually review the exact model error; "
                    "this is not evidence that the verifier rejects for the intended reason"
                    if intentional_invalid
                    else "invalid boundary envelope requires expected_action=reject"
                )
                results.append(
                    {
                        "case_id": case_id,
                        "status": "INVALID",
                        "annotation": annotation,
                        "detail": str(error),
                    }
                )
                if not intentional_invalid:
                    failed = True
            else:
                results.append({"case_id": case_id, "status": "INVALID", "detail": str(error)})
                failed = True
        else:
            results.append(
                {"case_id": case_id, "status": "VALID", "detail": "public model validation passed"}
            )
    return results, not failed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("corpus", type=Path, help="JSON generated by strict_case_builder.py")
    args = parser.parse_args()
    results, successful = preflight(args.corpus)
    for result in results:
        annotation = f" [{result['annotation']}]" if result.get("annotation") else ""
        print(f"{result['status']} {result['case_id'] or '-'}{annotation}: {result['detail']}")
    return 0 if successful else 1


if __name__ == "__main__":
    raise SystemExit(main())
